"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/src/shared/ui/button";
import { Input } from "@/src/shared/ui/input";
import { Label } from "@/src/shared/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/src/shared/ui/card";
import { useCreateSchool } from "@/src/modules/schools/application/useSchools";
import { ArrowLeft, Save, Loader2 } from "lucide-react";
import Link from "next/link";
import { School } from "@/src/core/types/domain";

export default function NewSchoolPage() {
    const router = useRouter();
    const { mutateAsync: createSchool, isPending } = useCreateSchool();

    const [formData, setFormData] = useState<Partial<School>>({
        name: "",
        slug: "",
        address: "",
        contactEmail: "",
        logoUrl: "",
        coverImageUrl: "",
        active: true,
    });

    const [phone, setPhone] = useState("");

    const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const name = e.target.value;
        const slug = name.toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/(^-|-$)+/g, '');

        setFormData(prev => ({ ...prev, name, slug }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            // We need to construct the full School object, but ID is generated by Repo
            // Wait, Repo.create expects Omit<School, "id" ...>
            // Let's check Repo signature.
            // Assuming Repo handles ID generation if not provided, or returns ID.
            // Actually, usually create returns ID.

            const schoolData = {
                ...formData,
                phone: phone, // Flattening phone for now as per simple schema, or use contactInfo if complex
                // The new domain model has phone at top level? Let's check.
                // Yes: phone?: string; contactEmail?: string;
                createdAt: new Date(),
                updatedAt: new Date(),
            } as any; // Type assertion for now to match Repo expectation

            const newSchoolId = await createSchool(schoolData);
            router.push(`/owner/schools/${newSchoolId}`);
        } catch (error) {
            console.error("Error creating school:", error);
            alert("Failed to create school.");
        }
    };

    return (
        <div className="max-w-2xl mx-auto space-y-8">
            <div className="flex items-center gap-4">
                <Link href="/owner/schools">
                    <Button variant="ghost" size="icon">
                        <ArrowLeft className="h-4 w-4" />
                    </Button>
                </Link>
                <h1 className="text-2xl font-bold text-gray-900">Add New School</h1>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>School Details</CardTitle>
                </CardHeader>
                <CardContent>
                    <form onSubmit={handleSubmit} className="space-y-6">
                        <div className="space-y-2">
                            <Label htmlFor="name">School Name</Label>
                            <Input
                                id="name"
                                required
                                value={formData.name}
                                onChange={handleNameChange}
                                placeholder="e.g. Springfield Elementary"
                            />
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="slug">URL Slug</Label>
                            <Input
                                id="slug"
                                required
                                value={formData.slug}
                                onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
                                placeholder="springfield-elementary"
                                className="font-mono"
                            />
                            <p className="text-xs text-muted-foreground">
                                Used in public URLs. Must be unique.
                            </p>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="contactEmail">Contact Email</Label>
                                <Input
                                    id="contactEmail"
                                    type="email"
                                    value={formData.contactEmail}
                                    onChange={(e) => setFormData({ ...formData, contactEmail: e.target.value })}
                                    placeholder="admin@school.com"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="phone">Phone</Label>
                                <Input
                                    id="phone"
                                    value={phone}
                                    onChange={(e) => setPhone(e.target.value)}
                                    placeholder="+1 (555) 000-0000"
                                />
                            </div>
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="address">Address</Label>
                            <Input
                                id="address"
                                value={formData.address}
                                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                                placeholder="123 School Lane"
                            />
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="logoUrl">Logo URL</Label>
                            <Input
                                id="logoUrl"
                                value={formData.logoUrl}
                                onChange={(e) => setFormData({ ...formData, logoUrl: e.target.value })}
                                placeholder="https://..."
                            />
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="coverImageUrl">Cover Image URL</Label>
                            <Input
                                id="coverImageUrl"
                                value={formData.coverImageUrl}
                                onChange={(e) => setFormData({ ...formData, coverImageUrl: e.target.value })}
                                placeholder="https://..."
                            />
                        </div>

                        <div className="pt-4">
                            <Button
                                type="submit"
                                className="w-full bg-indigo-600 hover:bg-indigo-700 text-white"
                                disabled={isPending}
                            >
                                {isPending ? (
                                    <>
                                        <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Creating...
                                    </>
                                ) : (
                                    <>
                                        <Save className="mr-2 h-4 w-4" /> Create School
                                    </>
                                )}
                            </Button>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </div>
    );
}
